spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

app:
  demo:
    enabled: ${DEMO_ENABLED:true}

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
